export const rooms = [
  {
    id: 1,
    hotelId: 1,
    type: 'Single',
    number: 1,
    maxVacancies: 1,
    availableVacancies: 0,
  },
  {
    id: 2,
    hotelId: 1,
    type: 'Double',
    number: 2,
    maxVacancies: 2,
    availableVacancies: 2,
  },
  {
    id: 3,
    hotelId: 1,
    type: 'Triple',
    number: 3,
    maxVacancies: 3,
    availableVacancies: 0,
  },
  {
    id: 4,
    hotelId: 1,
    number: 4,
    type: 'Single',
    maxVacancies: 1,
    availableVacancies: 1,
  },
  {
    id: 5,
    hotelId: 1,
    type: 'Double',
    number: 5,
    maxVacancies: 2,
    availableVacancies: 1,
  },
  {
    id: 6,
    hotelId: 1,
    type: 'Triple',
    number: 6,
    maxVacancies: 3,
    availableVacancies: 1,
  },
  {
    id: 7,
    hotelId: 1,
    number: 7,
    type: 'Single',
    maxVacancies: 1,
    availableVacancies: 1,
  },
  {
    id: 8,
    hotelId: 1,
    type: 'Double',
    number: 8,
    maxVacancies: 2,
    availableVacancies: 2,
  },
  {
    id: 9,
    hotelId: 1,
    type: 'Single',
    number: 9,
    maxVacancies: 1,
    availableVacancies: 1,
  },
  {
    id: 10,
    hotelId: 1,
    type: 'Double',
    number: 10,
    maxVacancies: 2,
    availableVacancies: 2,
  },
  {
    id: 11,
    hotelId: 1,
    type: 'Triple',
    number: 11,
    maxVacancies: 3,
    availableVacancies: 2,
  },
  {
    id: 12,
    hotelId: 1,
    number: 12,
    type: 'Single',
    maxVacancies: 1,
    availableVacancies: 1,
  },
  {
    id: 13,
    hotelId: 1,
    type: 'Double',
    number: 13,
    maxVacancies: 2,
    availableVacancies: 1,
  },
  {
    id: 14,
    hotelId: 1,
    type: 'Triple',
    number: 14,
    maxVacancies: 3,
    availableVacancies: 1,
  },
  {
    id: 15,
    hotelId: 1,
    number: 15,
    type: 'Single',
    maxVacancies: 1,
    availableVacancies: 1,
  },
  {
    id: 16,
    hotelId: 1,
    type: 'Double',
    number: 16,
    maxVacancies: 2,
    availableVacancies: 0,
  },
];
